#!/usr/bin/python

DOMAIN = "mintdesktop"
PATH = "/usr/share/linuxmint/locale"

import os, gettext, sys
sys.path.append('/usr/lib/linuxmint/common')
import additionalfiles

os.environ['LANG'] = "en_US.UTF-8"
gettext.install(DOMAIN, PATH)

prefix = "[Desktop Entry]\n"

suffix = """Exec=mintdesktop
Icon=user-desktop
Terminal=false
Type=Application
Encoding=UTF-8
Categories=GNOME;GTK;Settings;DesktopSettings;
StartupNotify=false
OnlyShowIn=MATE;
"""

additionalfiles.generate(DOMAIN, PATH, "usr/share/applications/mintDesktop.desktop", prefix, _("Desktop Settings"), _("Fine-tune desktop settings"), suffix)

