#!/usr/bin/env bash

WM=marco
BACKEND="glx"
VSYNC="opengl-swc"

if [ ! -x $(which ${WM}) ] && [ ! -x $(which compton) ]; then
    echo "ERROR! Can't find required components for ${WM} and compton."
    exit 1
fi

COMPTON_PIDS=$(pidof compton)
if [ $? -eq 0 ]; then
    echo "Killing compton"
    for PID in ${COMPTON_PIDS}; do
        kill -9 ${PID}
    done
fi

# Replace window manager and force compositing off.
${WM} --no-composite --replace &
sleep 1

# Allow users to override the defaults by creating their own config
# for this wrapper.
if [ -f ${HOME}/.config/${WM}-compton.conf ]; then
    compton --config ${HOME}/.config/${WM}-compton.conf -b
else
    compton --backend ${BACKEND} \
        --vsync ${VSYNC} \
        --shadow-ignore-shaped \
        --detect-rounded-corners \
        --paint-on-overlay \
        --glx-no-stencil \
        --glx-swap-method undefined \
        --unredir-if-possible \
        -r 10 -o 0.5 \
        -c -C -G -b \
        --shadow-exclude "! name~=''" \
        --shadow-exclude "name = 'Notification'" \
        --shadow-exclude "name = 'Plank'" \
        --shadow-exclude "name = 'Docky'" \
        --shadow-exclude "name = 'Kupfer'" \
        --shadow-exclude "name *= 'compton'" \
        --shadow-exclude "name *= 'Chromium'" \
        --shadow-exclude "name *= 'Chrome'" \
        --shadow-exclude "name *= 'Firefox'" \
        --shadow-exclude "class_g = 'Conky'" \
        --shadow-exclude "class_g = 'Kupfer'" \
        --shadow-exclude "class_g = 'Synapse'" \
        --shadow-exclude "class_g ?= 'Notify-osd'" \
        --shadow-exclude "class_g ?= 'Cairo-dock'" \
        --shadow-exclude 'window_type *= "menu"'

#--shadow-exclude "name *= 'VLC'" \
#--shadow-exclude 'argb && _NET_WM_OPAQUE_REGION@:c' # Fixes GTK3 double shadow
#--shadow-exclude "_GTK_FRAME_EXTENTS@:c"            # Fixes GTK3 double shadow
fi
