#!/usr/bin/env bash

WM=marco
BACKEND="glx"
VSYNC="opengl-swc"

if [ ! -x $(which ${WM}) ] && [ ! -x $(which compton) ]; then
    echo "ERROR! Can't find required components for ${WM} and compton."
    exit 1
fi

COMPTON_PIDS=$(pidof compton)
if [ $? -eq 0 ]; then
    echo "Killing compton"
    for PID in ${COMPTON_PIDS}; do
        kill -9 ${PID}
    done
fi

# Replace window manager and force compositing off.
${WM} --no-composite --replace &
sleep 1

# Allow users to override the defaults by creating their own config
# for this wrapper.
if [ -f ${HOME}/.config/${WM}-compton.conf ]; then
    compton --config ${HOME}/.config/${WM}-compton.conf -b
else
    compton --backend ${BACKEND} \
        --vsync ${VSYNC} \
        --paint-on-overlay \
        --glx-no-stencil \
        --glx-swap-method undefined \
        --unredir-if-possible \
        --inactive-dim 0.1 \
        --inactive-opacity-override \
        --mark-wmwin-focused \
        -r 7 -o 0.3 -l -7 -t -7 \
        -c -C -G -b \
        --shadow-exclude "! name~=''" \
        --shadow-exclude "name = 'Notification'" \
        --shadow-exclude "name = 'Plank'" \
        --shadow-exclude "name = 'Docky'" \
        --shadow-exclude "name = 'Kupfer'" \
        --shadow-exclude "name *= 'compton'" \
        --shadow-exclude "class_g = 'Conky'" \
        --shadow-exclude "class_g = 'Kupfer'" \
        --shadow-exclude "class_g = 'Synapse'" \
        --shadow-exclude "class_g ?= 'Notify-osd'" \
        --shadow-exclude "class_g ?= 'Cairo-dock'"

#       --detect-rounded-corners \
#       --shadow-exclude "_GTK_FRAME_EXTENTS@:c"    # Fixes GTK3 double shadow
fi
