#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Copyright (C) 2015 Martin Wimpress <code@ubuntu-mate.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.

import os
import shutil
import sys

def install_layout(filename):
    if os.path.exists(os.path.join('/','tmp',filename)):
        shutil.copy2(os.path.join('/','tmp',filename),
                     os.path.join('/','usr','share','mate-panel','layouts',filename))
        os.remove(os.path.join('/','tmp',filename))
    else:
        print('ERROR! Unable to find ' + os.path.join('/','tmp',filename))

def delete_layout(filename):
    if 'tweak' in filename:
        layout = os.path.join('/','usr','share','mate-panel','layouts',filename)
        if os.path.exists(layout):
            os.remove(layout)
        else:
            print('ERROR! Unable to find ' + layout)
    else:
        print('WARNING! I will only delete custom layouts. Skipping ' + layout)

if __name__ == '__main__':
    if len(sys.argv) == 3:
        action = sys.argv[1]
        if action == 'install':
            filename = sys.argv[2]
            install_layout(filename + '.layout')
            install_layout(filename + '.panel')
        elif action == 'delete':
            filename = sys.argv[2]
            delete_layout(filename + '.layout')
            delete_layout(filename + '.panel')
    else:
        print("ERROR! No action supplied.")
        sys.exit(1)
